### ISSUE TITLE
<postal>: new definition incomplete, also out of sync with implementation

### ISSUE THREAD

**Issue by reschke** [rfc-format/draft-iab-xml2rfc-v3-bis#101]
The grammar change in https://github.com/rfc-format/draft-iab-xml2rfc-v3-bis/pull/97/commits/4307135e5bf1ebe317ea0db3155a935e6c622bf2 (for https://github.com/rfc-format/draft-iab-xml2rfc-v3-bis/pull/97) is less complex than what the current implementation has: https://trac.tools.ietf.org/tools/xml2rfc/trac/browser/trunk/cli/xml2rfc/data/v3.rnc?rev=3348#L115. Would be good to understand why there is a discrepancy, and how it will get resolved. FWIW, the grammar in https://trac.tools.ietf.org/tools/xml2rfc/trac/browser/trunk/cli/xml2rfc/data/v3.rnc?rev=3348#L115 would be very confusing to explain.

**Comment by stpeter** [comment]
This appears to be overtaken by events.

**Comment by stpeter** [comment]
Closing because all postal issues will be addressed by https://github.com/rfc-format/draft-iab-xml2rfc-v3-bis/issues/137 and related changes.
