### ISSUE TITLE
document "special" Unicode characters

### ISSUE THREAD

**Issue by reschke** [rfc-format/draft-iab-xml2rfc-v3-bis#103]
As of xml2rfc v2.32.0, Unicode U+2028 is supported as forced line break.

Issue: we removed \<br>, and now we introduce something else offering the same?

Task: if this sticks, it needs to be documented 7991bis (note that RFC 7749 already had a section about this topic: https://greenbytes.de/tech/webdav/rfc7749.html#special.unicode.code.points)

**Comment by stpeter** [comment]
This issue might have been overtaken by events, i.e., it might have been raised around the time that we were also discussing the use of a br entity. Was U+2028 LINE SEPARATOR some kind of temporary workaround? If so, is this still a live issue?

**Comment by reschke** [comment]
It was a workaround.

I'm not sure whether it's still used. We also need to think about deprecating/removing the support for that from xm2rfc.

**Comment by stpeter** [comment]
Acknowledged. Apparently it is no longer used. Agreed on xml2rfc support, I'll make sure @rjsparks and team are aware.

**Comment by stpeter** [comment]
This might have already been addressed by https://trac.ietf.org/trac/xml2rfc/changeset/2987
