### ISSUE TITLE
misleading rational for deprecation of "alt" attribute

### ISSUE THREAD

**Issue by reschke** [rfc-format/draft-iab-xml2rfc-v3-bis#12]
See https://www.rfc-editor.org/errata_search.php?eid=4904

**Comment by paulehoffman** [comment]
I disagree that the rationale in the spec is misleading. The "alt" attribute was being used to provide a URL for a reference.

**Comment by reschke** [comment]
No, it was not; it was there to provide alternative text for an image (see https://greenbytes.de/tech/webdav/rfc7749.html#element.artwork.attribute.alt)
