### ISSUE TITLE
broken biblio entry for BCP 14

### ISSUE THREAD

**Issue by reschke** [rfc-format/draft-iab-xml2rfc-v3-bis#13]
See https://www.rfc-editor.org/errata_search.php?eid=4905

**Comment by paulehoffman** [comment]
It would be more constructive if this issue was titled "Problems with DOIs for BCPs" and had a better description of the underlying problem.

**Comment by reschke** [comment]
I agree that there's a general problem here, but that would be about the style guide.

This issue is about the concrete reference entry in *this* spec.

**Comment by reschke** [comment]
This was fixed in https://github.com/rfc-format/draft-iab-xml2rfc-v3-bis/commit/0af4bb876a9d17b1cda79be999d11bc6f965e232, prior to -00.
