### ISSUE TITLE
artwork and artset for text fallback

### ISSUE THREAD

**Issue by miekg** [rfc-format/draft-iab-xml2rfc-v3-bis#160]
I'm finally coming around of implementing svg images in mmark and just having an svg and creating an HTML doc works beautiful. 
But how is the text fallback supposed to work? Is that mandatory to create an RFC or will the HTML be canonical?

**Comment by miekg** [comment]
ok, according https://www.rfc-editor.org/rse/format-faq/ it is advised(?) to include both

**Comment by rjsparks** [comment]
Right - xml2rfc will process alternatives in an artset as per https://xml2rfc.tools.ietf.org/xml2rfc-doc.html#section-2.5.  If there's nothing available for a format (like txt) where SVG can't be rendered, and SVG is the only alternative, a string like "       (Artwork only available as SVG: see <docname>.html)" will be rendered.

The RFC Editor (or the appropriate stream manager) may push hard for there to be a reasonable alternative for txt formats, but it is not a requirement that the software should enforce.
