### ISSUE TITLE
ul@bare

### ISSUE THREAD

**Issue by mnot** [rfc-format/draft-iab-xml2rfc-v3-bis#169]
The 2.32 revision of the schema added the `bare` attribute to the `ul` element. This needs to be discussed and documented.

**Comment by reschke** [comment]
Also: https://trac.tools.ietf.org/tools/xml2rfc/trac/ticket/547

**Comment by stpeter** [comment]
Essentially these are list items where we didn’t want decoration. The origin of this was that RFC 7992 was very specific on how the table of contents was put together, and we wanted XML that generated the HTML table of contents from the prepped XML. The bare attribute was used to make this happen. Note that we’ve used this only in one RFC so far: https://www.rfc-editor.org/rfc/rfc8727.html#name-iodef-json-data-model

**Comment by reschke** [comment]
> and we wanted XML that generated the HTML table of contents from the prepped XML.

Which is an implementation choice which should not leak into the user-visible grammar.

**Comment by jrlevine** [comment]
added to 7991bis
