### ISSUE TITLE
deprecation of xref/@format='none' is bogus

### ISSUE THREAD

**Issue by reschke** [rfc-format/draft-iab-xml2rfc-v3-bis#17]
'none' covers the use case where *semantically* text refers to a \<reference>, but the generated text shouldn't show that.

For instance, it is very common to talk in prose about "RFC xxxx", and it's good if the XML source can express, that semantically this is indeed a reference, even if not styled that way. Example: first sentence of https://greenbytes.de/tech/webdav/rfc7990.html#rfc.section.3 - written by the RSE.

Technically, it's also helpful, as it keeps track of which references are actually used, and vice, versa, will cause an error if the reference target for some reason is removed from \<references>.

**Comment by reschke** [comment]
Also, citing https://greenbytes.de/tech/webdav/rfc7991.html#rfc.section.1.3.3

> Deprecate the "none" values for the "format" attribute in <xref> because it makes no sense semantically.

Even if that was true, that reasoning is bogus as we have lots of language features that "make no sense semantically".

**Comment by hildjj** [comment]
@paulehoffman
