### ISSUE TITLE
li@derivedCounter

### ISSUE THREAD

**Issue by mnot** [rfc-format/draft-iab-xml2rfc-v3-bis#170]
The 2.32 revision of the RNC added the `derivedCounter` to the `li` element. This should be discussed and documented.

**Comment by stpeter** [comment]
Note: 7991bis needs to specify that this is a derived attribute and should not to be included by authors in their source files.

**Comment by stpeter** [comment]
See also https://github.com/rfc-format/draft-iab-xml2rfc-v3-bis/issues/201

**Comment by jrlevine** [comment]
part of #201
