### ISSUE TITLE
xref attributes

### ISSUE THREAD

**Issue by mnot** [rfc-format/draft-iab-xml2rfc-v3-bis#172]
The 2.32 revision of the schema added the `sectionFormat`, `section`, `relative` and `derivedLink` attributes to the `xref` element. These changes should be discussed and documented.

**Comment by stpeter** [comment]
Discussion in the change management team led to the conclusion that (a) relref has not been used in source documents provided by authors and (b) if it had been used, the xml2rfc tool would have transformed relref to xref while adding any of the attributes defined in RFC 7991 for relref but not xref (sectionFormat, section, relative, derivedLink). Therefore our recommendation is to deprecate relref in 7991bis and likely add some or all of the relref attributes to xref. I've posted about this to rfc-interest and we can discuss there.
