### ISSUE TITLE
relref@derivedContent

### ISSUE THREAD

**Issue by mnot** [rfc-format/draft-iab-xml2rfc-v3-bis#173]
The 2.32 revision of the schema added the `derivedContent` attribute to the `relref` element. This change should be discussed and documented.

**Comment by jrlevine** [comment]
We'll be deprecating <relref> since it is completely unused.

**Comment by stpeter** [comment]
See also https://github.com/rfc-format/draft-iab-xml2rfc-v3-bis/issues/184

**Comment by stpeter** [comment]
Closing this in favor of #184 - we do need to document derivedContent as part of that.
