### ISSUE TITLE
artset element

### ISSUE THREAD

**Issue by mnot** [rfc-format/draft-iab-xml2rfc-v3-bis#175]
The 2.32 revision of the schema added the `artset` element. This change should be discussed.

**Comment by reschke** [comment]
See <https://github.com/rfc-format/draft-iab-xml2rfc-v3-bis/issues/76>

**Comment by mnot** [comment]
Fair enough (although a pretty thin discussion).

**Comment by jrlevine** [comment]
added to 7991bis
