### ISSUE TITLE
default value for [td, th]@[colspan, rowspan]  (backwards-incompatible change)

### ISSUE THREAD

**Issue by mnot** [rfc-format/draft-iab-xml2rfc-v3-bis#177]
The 2.32 revision of the schema change the defaults of the `colspan` and `rowspan` attributes for the `td` and `th` elements from `0` to `1`. 

This is a backwards-incompatible change. It should be discussed and documented.

**Comment by jrlevine** [comment]
Zero default was a mistake. This was corrected in xml2rfc in 2019.

https://datatracker.ietf.org/doc/html/draft-levkowetz-xml2rfc-v3-implementation-notes#section-3.1.29

**Comment by jrlevine** [comment]
updated in 7991bis
