### ISSUE TITLE
reference@quote-title (backwards-incompatible change)

### ISSUE THREAD

**Issue by mnot** [rfc-format/draft-iab-xml2rfc-v3-bis#179]
The 2.32 revision of the schema added the `quote-title` attribute to the `reference` element. The current 7991bis documents it, but removes `quoteTitle`, which was defined by 7991, without any explanation. This is not backwards-compatible.

**Comment by reschke** [comment]
See <https://github.com/rfc-format/draft-iab-xml2rfc-v3-bis/issues/48> for context.

**Comment by stpeter** [comment]
Closing this issue in favor of #48
