### ISSUE TITLE
x:include nits

### ISSUE THREAD

**Issue by reschke** [rfc-format/draft-iab-xml2rfc-v3-bis#18]
1) Reference should be updated to point to https://www.w3.org/TR/2006/REC-xinclude-20061115/

2) (It should be clarified how much of XInclude needs to be supported. I'm mentioning this because RFC7991 says that includes can not happen where no elements are allowed, but XInclude allows inclusion of plain text as well.)

3) (Is support of the xpointer attribute required? If so, do we have any guidance how this will work when the document from which to include uses xml2rfc format, and the pointer relies on the id-ness of an attribute?)

4) The final example uses the namespace prefix "x:", while the preceding text uses "xi:".

**Comment by hildjj** [comment]
1. Agree

2. There are uses for plain text, but I understand your point.  Want other opinions.

3. If the answer to 2 is "not everything", then yes, we should disallow xpointer.

4. Bug.

**Comment by reschke** [comment]
Moved points 2. and 3. to https://github.com/rfc-format/draft-iab-xml2rfc-v3-bis/issues/128

**Comment by reschke** [comment]
5. add a note about the line breaks in the example
