### ISSUE TITLE
xref content model

### ISSUE THREAD

**Issue by mnot** [rfc-format/draft-iab-xml2rfc-v3-bis#184]
RFC7991 (and bis) define the content model of `xref` as "only text content". 

Revision 2.35 of the RNC added markup -- namely, `em`, `strong`, `sub`, `sup`, and `tt`. This should be discussed and documented.

**Comment by stpeter** [comment]
This is documented more completely at https://xml2rfc.tools.ietf.org/xml2rfc-doc.html#name-xref-2 and that needs to be ported over to 7991bis. Labeled as WILL DOCUMENT.

**Comment by jrlevine** [comment]
added to 7991bis
