### ISSUE TITLE
contact element

### ISSUE THREAD

**Issue by mnot** [rfc-format/draft-iab-xml2rfc-v3-bis#185]
Revision 2.37 of the RNC introduced the `contact` element. This should be discussed and documented.

**Comment by reschke** [comment]
See <https://github.com/rfc-format/draft-iab-xml2rfc-v3-bis/issues/81>

**Comment by stpeter** [comment]
There's better documentation at https://xml2rfc.tools.ietf.org/xml2rfc-doc.html#name-contact-new-2  but it needs to be added to 7991bis. This will be documented.

**Comment by jrlevine** [comment]
added to 7991bis
