### ISSUE TITLE
br element

### ISSUE THREAD

**Issue by mnot** [rfc-format/draft-iab-xml2rfc-v3-bis#187]
The `br` element seems to come and go in the schema; currently, it exists there, but not in RFC7991bis-03. This should be discussed, settled, and documented.

**Comment by stpeter** [comment]
The RPC's guidance has been to use `<br>` not `&br;` but to use `<br>` sparingly since in general it should be possible to use other markup to get the desired output. Thus I think the recommendation is to retain the element but document it further in 7991bis and the style guide.

**Comment by jrlevine** [comment]
documented in 7991bis
