### ISSUE TITLE
address/email

### ISSUE THREAD

**Issue by mnot** [rfc-format/draft-iab-xml2rfc-v3-bis#188]
Revision 2.46 of the RNC added the ability for an `address` to contain multiple `email` elements. This is not documented in RFC7991bis.

**Comment by reschke** [comment]
See <https://github.com/rfc-format/draft-iab-xml2rfc-v3-bis/issues/4>

**Comment by stpeter** [comment]
It seems that we have agreement in https://github.com/rfc-format/draft-iab-xml2rfc-v3-bis/issues/4 and thus can close this issue.

**Comment by jrlevine** [comment]
in 7991bis
