### ISSUE TITLE
aside/blockquote

### ISSUE THREAD

**Issue by mnot** [rfc-format/draft-iab-xml2rfc-v3-bis#190]
Revision 3.0.0 of the RNC allows `blockquote` to appear inside `aside`. This needs to be discussed and documented.

**Comment by stpeter** [comment]
For traceability, see https://trac.tools.ietf.org/tools/xml2rfc/trac/ticket/524 and https://github.com/rfc-format/draft-iab-xml2rfc-v3-bis/issues/84 and https://github.com/rfc-format/draft-iab-xml2rfc-v3-bis/pull/155 for further context.

**Comment by jrlevine** [comment]
Accept and document in 7991bis

**Comment by jrlevine** [comment]
Accept and document in 7991bis

**Comment by jrlevine** [comment]
added to 7991bis
