### ISSUE TITLE
sup and sub in sup and sub

### ISSUE THREAD

**Issue by mnot** [rfc-format/draft-iab-xml2rfc-v3-bis#193]
Revision 3.0.0 of the RNC added `sub` and `sup` into the content models of `sub` and `sup`. This needs to be documented.

**Comment by stpeter** [comment]
FWIW, Henrik has tested up to three levels of sup within sup or sup within sub and it rendered fine. The intent is that this will not provide anything close to complete math support, only the right level of support for subscripts and superscripts so that we can easily document crypto algorithms.

**Comment by jrlevine** [comment]
added to 7991bis
