### ISSUE TITLE
Consider generating Contributors section

### ISSUE THREAD

**Issue by hildjj** [rfc-format/draft-iab-xml2rfc-v3-bis#2]
There are likely several approaches; adding a new author role of "contributor" is one of them.

**Comment by hildjj** [comment]
See thread starting here: https://www.rfc-editor.org/pipermail/rfc-interest/2016-December/009765.html

**Comment by paulehoffman** [comment]
I'm going to close this as being too adventurous for this revision. It is an interesting idea, however.
