### ISSUE TITLE
Knob to control rendering of Authors' organisations on the first page.

### ISSUE THREAD

**Issue by levkowetz** [rfc-format/draft-iab-xml2rfc-v3-bis#20]
Guidance from the IAB regarding IAB stream documents (​https://www.rfc-editor.org/materials/iab-format.txt) indicate that "'Each author's name SHOULD be listed without an organization.".

See xml2rfc ticket #311, https://trac.tools.ietf.org/tools/xml2rfc/trac/ticket/311

There's currently no control which makes this possible.

One option explored in the ticket is to trigger this off the submissionType, but there are IAB documents which are published with organisation lines, so there doesn't seem to be a one-to-one relationship between the submissionType and omitting organisation information.

Another option mentioned is to add an attribute on the organization element, "suppressOnFrontPage", but that violates DRY; one would have to do that on each author block when there are multiple authors, which seems wrong.

Thoughts?

**Comment by reschke** [comment]
> One option explored in the ticket is to trigger this off the submissionType, but there are IAB documents which are published with organisation lines, so there doesn't seem to be a one-to-one relationship between the submissionType and omitting organisation information.

FWIW, this seems to be the case for *all* documents published about the new RFC format (7990-7998).

> Another option mentioned is to add an attribute on the organization element, "suppressOnFrontPage", but that violates DRY; one would have to do that on each author block when there are multiple authors, which seems wrong.

We could move it up the hierarchy, in doubt to \<front> or \<rfc>.

**Comment by levkowetz** [comment]
On 2017-05-31 12:29, Julian Reschke wrote:
>> One option explored in the ticket is to trigger this off the
>> submissionType, but there are IAB documents which are published
>> with organisation lines, so there doesn't seem to be a one-to-one
>> relationship between the submissionType and omitting organisation
>> information.
> 
> FWIW, this seems to be the case for *all* documents published about
> the new RFC format (7990-7998).
> 
>> Another option mentioned is to add an attribute on the organization
>> element, "suppressOnFrontPage", but that violates DRY; one would
>> have to do that on each author block when there are multiple
>> authors, which seems wrong.
> 
> We could move it up the hierarchy, in doubt to \<front> or \<rfc>.

suppressAuthorOrgOnFrontPage (or something shorter but intelligible)
on \<front> or \<rfc> would work for me.


	Henrik

**Comment by reschke** [comment]
See <https://mailarchive.ietf.org/arch/msg/xml2rfc/6TZi9BEg9lPoPNQuKBfl07HYml4>.

**Comment by reschke** [comment]
@interim-rfc-series-project-manager - this can be closed, see https://github.com/rfc-format/draft-iab-xml2rfc-v3-bis/pull/93
