### ISSUE TITLE
<sourcecode/> "name" attribute rename?

### ISSUE THREAD

**Issue by levkowetz** [rfc-format/draft-iab-xml2rfc-v3-bis#22]
[RFC 6087](https://tools.ietf.org/html/rfc6087#section-3.1) specifies a format for the file name associated with a yang module within `<CODE BEGINS>` / `<CODE ENDS>` delimiters, exaplified with:
```
   <CODE BEGINS> file "ietf-foo@2010-01-18.yang"
   module ietf-foo {
       // ...
      revision 2010-01-18 {
         description "Latest revision";
         reference "RFC XXXX";
      }
      // ...
   }
   <CODE ENDS>
```
It seems 1) like a good idea to use this rendering for v3, and 2) to match the file name attribute of <sourcecode/> with the 'file' keyword in the rendering; i.e., change the attribute name 'name' to 'file'.

**Comment by reschke** [comment]
I see two questions here:

1) If we have filename information, how should it be displayed? https://www.greenbytes.de/tech/webdav/rfc7992.html#element.sourcecode is currently silent about that.

2) What's the best attribute name in the v3 vocab for that?

**Comment by levkowetz** [comment]
Ack.  Sorry for multiple questions in the same issue.

**Comment by pkyzivat** [comment]
I think there should be clarification about the context in which the name is interpreted. (Is the the file system of the system where the xml file is stored? If so, what is the current directory there? What kind of file system naming limitations?)  Is it permissible to use directory structuring (relative or absolute) in the names?

Or should this be left loose while allowing deployments to nail it down? (E.g. the IETF might define this for RFCs and drafts.)

Can this be specified so that things will still work if the xml is rehomed to a different system?

**Comment by reschke** [comment]
At the end of the day, this is just a hint, similar to the filename parameter in a Content-Disposition response header fields.

Do you see a use case where anything but a simple filename is needed?

**Comment by pkyzivat** [comment]
I'm uncertain where to draw the line between the abstract syntax and deployment conventions. I'm concerned with usage within the IETF deployment. As I mentioned elsewhere, I think it would be good to have a conceptual directory associated with each document that contains these things. 

This of course assumes there is some way to list and access the contents of this directory. That part is IMO out of scope for *this* specification. But it could be defined as part of the datatracker.

While I don't have a particular usage in mind I can imagine in a document with many pieces of example sourcecode organized into different sections it might be helpful to organize them into sub-directories. But of course its also possible to do something similar using a naming convention within the document.

I was also thinking that it might be helpful if there was a sub-directory peer sourcecode type. But that could be a convention of the datatracker.

Perhaps the answer is just to leave the specification as it is *here*, being vague. And then something else that defines how these names are mapped onto some accessible structure for ietf documents.

**Comment by stpeter** [comment]
The sense of the XML change management team is that we have quite a few published documents with `name` and there isn't a compelling reason to change the attribute name, but clearer guidance to authors might be needed. We suggest marking this as WONTFIX.
