### ISSUE TITLE
<relref> description broken with respect to use of "relative"

### ISSUE THREAD

**Issue by reschke** [rfc-format/draft-iab-xml2rfc-v3-bis#23]
<https://www.greenbytes.de/tech/webdav/rfc7991.html#rfc.section.2.44.p.2>:

> The "section" attribute is required, and the "relative" attribute is optional. If the reference is not an RFC or Internet-Draft that is in the v3 format, the element needs to have a "relative" attribute; in this case, the value of the "section" attribute is ignored.

That is incorrect. In the case where there is no text content, it will still be needed in the generated text.

**Comment by stpeter** [comment]
Overtaken by events: https://github.com/rfc-format/draft-iab-xml2rfc-v3-bis/issues/26
