### ISSUE TITLE
<relref> misleading example

### ISSUE THREAD

**Issue by reschke** [rfc-format/draft-iab-xml2rfc-v3-bis#24]
<https://www.greenbytes.de/tech/webdav/rfc7991.html#rfc.section.2.44.p.3>:

      See
      <relref section="2.3" target="RFC9999" displayFormat="bare">
      the protocol overview</relref>
      for more information.

But <https://www.greenbytes.de/tech/webdav/rfc7991.html#rfc.section.2.44.1.p.1>:

> ... If there is content in the \<relref> element, formatters will ignore the value of this attribute.

**Comment by stpeter** [comment]
Overtaken by events: https://github.com/rfc-format/draft-iab-xml2rfc-v3-bis/issues/26
