### ISSUE TITLE
Formatting details for section heading text

### ISSUE THREAD

**Issue by davecrocker** [rfc-format/draft-iab-xml2rfc-v3-bis#3]
Evaluate spacing before heading, so it is not excessive.  Evaluate heading font size, so it isn't too large.  Consider non-black (dark) color for heading text.  (eg, dark blue.)

**Comment by reschke** [comment]
I don't think this applies to the vocabulary draft.

**Comment by paulehoffman** [comment]
Agree that this does not apply to the vocabulary.

**Comment by reschke** [comment]
@davecrocker  - FWIW, this should be covered by the CSS design.
