### ISSUE TITLE
<name> tag can contain <tt> but no <em>

### ISSUE THREAD

**Issue by miekg** [rfc-format/draft-iab-xml2rfc-v3-bis#32]
The `<name>` tag (for a section) (see https://tools.ietf.org/html/rfc7991#section-2.32), can contain a `<tt>`, but an `<em>` is not allowed.

However the `<tt>` element can have, among others the `<em>` as  a child. This is some what inconsistent.

**Comment by levkowetz** [comment]
On 2018-08-25 09:47, Miek Gieben wrote:
> The `<name>` tag (for a section) (see https://tools.ietf.org/html/rfc7991#section-2.32), can contain a `<tt>`, but an `<em>` is not allowed.
> 
> However the `<tt>` element can have, among others the `<em>` as  a child. This is some what inconsistent.


Agreed.  See:

  https://tools.ietf.org/html/draft-levkowetz-xml2rfc-v3-implementation-notes-00#section-3.1.5


	Henrik

**Comment by reschke** [comment]
@interim-rfc-series-project-manager - this can be closed; see #47 and #69

**Comment by jrlevine** [comment]
See #47 and #69
