### ISSUE TITLE
`<artwork>` src and content confusion

### ISSUE THREAD

**Issue by miekg** [rfc-format/draft-iab-xml2rfc-v3-bis#34]
Section 2.5
>  Alternatively, the "src" attribute allows referencing an external
   graphics file, such as a vector drawing in SVG or a bitmap graphic
   file, using a URI.  In this case, **the textual content acts as a
   fallback for output representations** that do not support graphics;
   thus, it ought to contain either (1) a "line art" variant of the
   graphics or (2) prose that describes the included image in sufficient
   detail.

And later:
> It is an error to have both a "src" attribute and content in the
   \<artwork> element.

**Comment by paulehoffman** [comment]
Fixed by #43
