### ISSUE TITLE
`<li>` can't contain a block quote

### ISSUE THREAD

**Issue by miekg** [rfc-format/draft-iab-xml2rfc-v3-bis#35]
The `<li`> element https://tools.ietf.org/html/rfc7991#section-2.29 can contain quite a bit of block elements, except `<blockquote>` (among others I think). Why?

In v2 xml ones usually works around this by mimicking the layout by abusing another element. Seems strange to do this here as well.

**Comment by paulehoffman** [comment]
Fixed by #51

**Comment by reschke** [comment]
@interim-rfc-series-project-manager - this issue can be closed, see https://github.com/rfc-format/draft-iab-xml2rfc-v3-bis/pull/51
