### ISSUE TITLE
Schema Issue, RFC 7991, In Section 2.12, <br>

### ISSUE THREAD

**Issue by levkowetz** [rfc-format/draft-iab-xml2rfc-v3-bis#37]
In Section 2.12, \<br>

   A number of elements permits a mixed content model (see Section "Mixed
   Content Model"): \<li>, \<blockquote>, \<dd>, \<td>, and \<th>.  However,
   when using the simpler of the two content schemas, two of them (\<td> and
   \<th>) permit inline line breaks through the use of \<br> elements; the
   others do not.  This seems terribly arbitrary.

   Recommendation:  Remove the \<br> element completely.  Alternatively,
                    permit it to be used all places that 'text' and non-
                    block elements may be used (that is, in inline
                    context).

   Implementation:  The current version of xml2rfc renders \<br> as a
                    newline in all inline contexts.

**Comment by reschke** [comment]
As far as I recall, we ended up with the limited use of \<br> because forcing a line break inside a table cell sometimes really is needed, while otherwise it's not. I agree consistency is nice, but this may be a case where the current approach is the right one.

**Comment by miekg** [comment]
Are we still expecting humans to write this XML directly? I ask because the
number of one-offs is already staggering (esp. with attribute naming and
the number of them).

I would hope to see some simplification of the spec, which I this case
means allowing br in more places or disallowing the element entirely.

**Comment by reschke** [comment]
> Are we still expecting humans to write this XML directly? I ask because the
Some will.

> number of one-offs is already staggering (esp. with attribute naming and
> the number of them).

What do you mean by "one-off"?

> I would hope to see some simplification of the spec, which I this case
> means allowing br in more places or disallowing the element entirely.

Well, I explained why it is like it is right now (as far as I recall). I also think that these reasons are more important than consistency.

Do you think that you need <br> in other places? 

Do you think that we can get rid of it in table cells?

**Comment by levkowetz** [comment]
From the list:

**Comment by TonyLHansen** [comment]
Please re-open, based on evidence that the RPC needs the capability, and <br/> is better than the alternatives.

**Comment by stpeter** [comment]
During discussion in the XML change management team, the RPC reported that this feature is indeed useful at times to provide fine-grained control over line breaks in table cells especially, so retaining the feature seems like the best route for now.

**Comment by TonyLHansen** [comment]
Should the alternative that Henrik recommended be chosen instead?

"Alternatively,
permit it to be used all places that 'text' and non-
block elements may be used (that is, in inline
context)."
