### ISSUE TITLE
Schema Issue, RFC 7991, New Section 2.20.4, "indent" Attribute

### ISSUE THREAD

**Issue by levkowetz** [rfc-format/draft-iab-xml2rfc-v3-bis#39]
New Section 2.20.4, "indent" Attribute

   The deprecation of the "hangIndent" attribute on \<list> leaves no
   opportunity to control the size of the hanging indent.  In some
   definition lists, it is desirable to have a wide indentation, in order
   to clearly show the terms, in other cases it is more important to allow
   for a larger text volume than the width of the terms would allow.

   Recommendation:  Add an "indent" attribute on \<dl> to control the size
                    of the hanging indent.

   Implementation:  The current version of xml2rfc does not support the
                    attribute, but has all the underlying functions needed
                    to apply such an attribute.  Internally, an indentation
                    is calculated based on length of the \<dt> text and the
                    settings of some of the other attributes.

**Comment by reschke** [comment]
I agree that this would be useful - however we'll need to define it in a way that works well with non-monospaced fonts.

**Comment by levkowetz** [comment]
Closed with acceptance of 'indent' attribute after discussion on the list:
https://mailarchive.ietf.org/arch/browse/xml2rfc-dev/?q=subject%3A%2339

**Comment by reschke** [comment]
@levkowetz - I note that xml2rfc supports "indent" on all list types, not only on \<dl>. Is that intentional? What is the use case?
