### ISSUE TITLE
<email> cardinality

### ISSUE THREAD

**Issue by reschke** [rfc-format/draft-iab-xml2rfc-v3-bis#4]
(from https://tools.ietf.org/tools/xml2rfc/trac/ticket/36)

reference.RFC.2507.xml has two email addresses for one of the authors, which breaks formatting in "strict" mode.

This seems to be on purpose; the RFC indeed specifies two comma, separated addresses.

We either need to fix the generation script, or xml2rfc's DTD. 

 Looking at my collection of RFCs, this seems to be used now and then;

rfc4844.unpg: EMail: ​ledaigle@cisco.com, ​leslie@thinkingcat.com
rfc4845.unpg: EMail: ​ledaigle@cisco.com, ​leslie@thinkingcat.com
rfc5741.unpg: EMail: ​daigle@isoc.org, ​leslie@thinkingcat.com
rfc6185.unpg: EMail: ​tom.kristensen@tandberg.com, ​tomkri@ifi.uio.no
rfc7269.unpg: EMail: ​chengang@chinamobile.com, ​phdgang@gmail.com
rfc7269.unpg: EMail: ​caozhen@chinamobile.com, ​zehn.cao@gmail.com
rfc7445.unpg: EMail: ​phdgang@gmail.com, ​chengang@chinamobile.com

**Comment by paulehoffman** [comment]
This seems more like a feature request for \<address\> than for \<email\>. An easy solution would be to allow zero-or-more of any of the children in \<address\>, not just zero-or-one.

**Comment by reschke** [comment]
More recent uses:

~~~
rfc7269.orig:   EMail: chengang@chinamobile.com, phdgang@gmail.com
rfc7269.orig:   EMail: caozhen@chinamobile.com, zehn.cao@gmail.com
rfc7445.orig:   EMail: phdgang@gmail.com, chengang@chinamobile.com
rfc7597.orig:   Email: phdgang@gmail.com, chengang@chinamobile.com
rfc7599.orig:   Email: phdgang@gmail.com, chengang@chinamobile.com
rfc7600.orig:   Email: phdgang@gmail.com, chengang@chinamobile.com
rfc7642.orig:   Email: vumip1@gmail.com, bhumip.khasnabish@ztetx.com
rfc7716.orig:   Email: meng.wei2@zte.com.cn,vally.meng@gmail.com
rfc7729.orig:   Email: vumip1@gmail.com, bhumip.khasnabish@ztetx.com
rfc7849.orig:   Email: phdgang@gmail.com, chengang@chinamobile.com
~~~

**Comment by reschke** [comment]
see https://github.com/rfc-format/draft-iab-xml2rfc-v3-bis/pull/143 - @levkowetz - is this something you would add in xml2rfc?

**Comment by reschke** [comment]
Feature request for xml2rfc in https://trac.tools.ietf.org/tools/xml2rfc/trac/ticket/522

**Comment by stpeter** [comment]
FWIW I agree with @paulehoffman - allow zero-or-more instances of any child of the `address` element. This would also solve https://github.com/rfc-format/draft-iab-xml2rfc-v3-bis/issues/161
