### ISSUE TITLE
Schema Issue, RFC 7991, New Section 2.54.2

### ISSUE THREAD

**Issue by levkowetz** [rfc-format/draft-iab-xml2rfc-v3-bis#40]
New Section 2.54.2

   The version 3 schema deprecates the previously available 'align'
   attribute for the tables, and the V2 to V3 converter will remove this
   attributes if used.  This makes a previous feature that was appreciated
   by some authors unavailable.  In the text formatter, the effect is
   simply to make all tables left-aligned, which may not be the most
   readable and polished output, but for the HTML formatter it also
   potentially removes the option of letting text flow around smaller
   tables in a controlled way.

   Recommendation:  Make the 'align' attribute for tables available again.

   Implementation:  Implemented but inactive in the current version of
                    xml2rfc.  The current text formatter code already has
                    support for the 'align' attribute for these elements;
                    but since the schema does not permit the attribute for
                    \<table>, the code is never invoked.

**Comment by reschke** [comment]
+1, but duplicated <https://github.com/rfc-format/draft-iab-xml2rfc-v3-bis/issues/9>
