### ISSUE TITLE
target audience for writing XML?

### ISSUE THREAD

**Issue by miekg** [rfc-format/draft-iab-xml2rfc-v3-bis#41]
Do we target humans writing XML directly, or it this spec mean to for other languages (i.e. markdown) to compile to.

If "humans" would should aim (IMO) for a consistent spec where attribute names are consistent and not that numerous and there aren't a lot of exceptions on where what elements can be used.

If we let something compile to XML we could relax this is bit. Although my experience with using markdown is that a lot of the details carry over to the markdown as well; making it easy to generate an illegal document

**Comment by reschke** [comment]
> If "humans" would should aim (IMO) for a consistent spec where attribute names are consistent and not that numerous and there aren't a lot of exceptions on where what elements can be used.

If you have issues with *new* attribute names, please open separate issues.

Exceptions are there for a good reason; if you believe a specific one should be lifted, please open a separate issue and explain why you the exception should be removed.

**Comment by levkowetz** [comment]
I actually think that this is a valid issue for the overall vocabulary.  If we don't permit this to be expressed as an issue with the overall user-friendliness of the vocabulary, there is no single element or attribute to point at, which would mean that disallowing it says that we're disallowing user-friendliness to be a consideration for the schema as a whole.  I don't think that would be right.

**Comment by levkowetz** [comment]
On 2018-10-03 09:52, Julian Reschke wrote:
>> If "humans" would should aim (IMO) for a consistent spec where
>> attribute names are consistent and not that numerous and there
>> aren't a lot of exceptions on where what elements can be used.
> 
> If you have issues with *new* attribute names, please open separate
> issues.
> 
> Exceptions are there for a good reason; if you believe a specific one
> should be lifted, please open a separate issue and explain why you
> the exception should be removed.

I actually think that this is a valid issue for the overall vocabulary.
If we don't permit this to be expressed as an issue with the overall
user-friendliness of the vocabulary, there is no single element or
attribute to point at, which would mean that disallowing it says that
we're disallowing user-friendliness to be a consideration for the
schema as a whole. I don't think that would be right.

Regards,

	Henrik

**Comment by paulehoffman** [comment]
Could you please take this discussion to the mailing list? Miek: when I asked you to open the issue, I also hoped you would take it to the list like Henrik has with his issues.

**Comment by stpeter** [comment]
It seems we don't need to track this as an active issue here, since this should be discussed on the rfc-interest list.
