### ISSUE TITLE
Schema Issue, RFC 7991, In Section 2.29, <li>, Unordered lists with arbitrary symbols

### ISSUE THREAD

**Issue by levkowetz** [rfc-format/draft-iab-xml2rfc-v3-bis#45]
Unordered lists with arbitrary symbols

   When \<li> is used with \<ul empty="true">, the rendering is under-
   specified (the specification says 'no label will be shown", but doesn't
   say whether list indentation (leading white-space) should be eliminated
   or not.

   If the intention is to make it possible to render unordered lists with
   arbitrary symbols, chosen on a per-list-item basis, the current
   attributes of \<li> are insufficient to indent and line-wrap list items
   properly with \<ul empty='true'>.

   It is not possible, for instance, to use \<ul> lists to generate XML for
   a table of content, since if the width of the bullet (the section
   number, in this case) is unknown, the proper indentation and line
   wrapping cannot be determined.

   Proposal:        Add an explicit "bullet" attribute to support this use
                    case.

   Implementation:  None in the current version of xml2rfc, but internally
                    bullets are taken a configurable bullet list, so
                    accommodating such an attribute would be trivial.

**Comment by paulehoffman** [comment]
From the mailing list:
Issue #45 - consensus reached: leave spec as is wrt <li> and layout for unordered lists
