### ISSUE TITLE
Schema Issue, RFC 7991, In Section 2.29, <li>, Mixed Content Model

### ISSUE THREAD

**Issue by levkowetz** [rfc-format/draft-iab-xml2rfc-v3-bis#46]
Mixed Content Model

   The mixed content model for \<li> —- either text and inline elements like
   sub, sup, bcp14, _or_ \<t>, \<ul>, \<figure> etc, is non-intuitive and may
   be hard for users to keep straight.

   Proposal:        Consider simplifying the schema by requiring that text
                    and inline elements always are placed within a \<t>
                    element.

   Implementation:  Not done in the current version of xml2rfc.

   This would apply also to other elements that today have alternative
   content models: \<blockquote>, \<dd>, \<td>, and \<th>.

**Comment by paulehoffman** [comment]
From the mailing list:
Issue #46 - consensus reached: leaved spec as is wrt <li> mixed content model
