### ISSUE TITLE
Schema Issue, RFC 7991, In Section 2.32, <name>

### ISSUE THREAD

**Issue by levkowetz** [rfc-format/draft-iab-xml2rfc-v3-bis#47]
In Section 2.32, \<name>

   So the \<name> element can contain text or \<tt>, and \<tt> can contain
   other markup like \<sub> and \<sup> etc., but why cannot \<name> contain
   \<sup> etc.  directly?

   Proposal:        Change the \<name> element schema to permit all inline
                    elements that \<tt> can contain, in addition to \<tt>.

   Implementation:  Not changed in the current version of xml2rfc.
                    Implementing this would be a simple matter of changing
                    the v3 schema; no formatter changes would be needed.

**Comment by paulehoffman** [comment]
Consensus was to implement.

**Comment by paulehoffman** [comment]
Closed with PR #69

**Comment by reschke** [comment]
(duplicate of #32 )
