### ISSUE TITLE
Schema Issue, RFC 7991, In Section 2.40.2, "quoteTitle"

### ISSUE THREAD

**Issue by levkowetz** [rfc-format/draft-iab-xml2rfc-v3-bis#48]
In Section 2.40.2, "quoteTitle"

   The version two xml2rfc processors already support the attribute "quote-
   title".  The attribute name change introduces an incompatibility.  This
   in particular impacts existing bibxml reference files, which should work
   with both version 2 and 3 vocabulary documents.

   Proposal:        Change the attribute name back to the value supported
                    by the vocabulary version 2 modes of xml2rfc.

   Implementation:  The current version of xml2rfc converts "quote-title"
                    to "quoteTitle" during v2v3 conversion, but this is
                    really sub-optimal.

**Comment by reschke** [comment]
The intent was that the v2 converter would implement the new attribute name as soon as possible - around three years ago. The reason for picking a different attribute name was consistency with the rest of the vocabulary.

\<reference> entries can be fixed, and nothing stops a specific implementation to accept the incorrect spelling in a lax mode (both in v2 and v3 mode).

**Comment by reschke** [comment]
FWIW, I just checked the \<reference> elements included by ~2400 XML files used in AUTH48 for RFC production. They included ~1800 different references (using the URI as key), and none of these uses quote-title or quoteTitle.

Either I did something wrong here, or there simply is no backwards compat issue.

**Comment by stpeter** [comment]
AIUI based on discussion the XML change management team, currently if quote-title is found in a source file it is converted to quoteTitle by the preptool. In submitted I-Ds we see both but as of v3 only quoteTitle should show up in RFCs. We suggest it's best to document that both exist but only quoteTitle is valid in the published format.

**Comment by jrlevine** [comment]
Done in -04
