### ISSUE TITLE
remove <tfoot>

### ISSUE THREAD

**Issue by reschke** [rfc-format/draft-iab-xml2rfc-v3-bis#5]
(from https://tools.ietf.org/tools/xml2rfc/trac/ticket/319)

It's not clear that we need \<tfoot\>. In HTML it's used for information that will repeat at the end of the table (on each page, when paginating).

**Comment by paulehoffman** [comment]
Can you say more about "It's not clear that we need"? What is the problem with keeping \<tfoot\>? Why is this different than \<thead\>?

**Comment by reschke** [comment]
1) If you think we need it, can you provide an example?

2) \<thead> is different in that most tables we use have indeed column titles.

**Comment by ronaldtse** [comment]
Here's an example where I the presence of `<tfoot>` would help:

https://tools.ietf.org/html/draft-ribose-cfrg-sm4-05

```
    +--------------------+--------------------------------------------+
    |                    |              Algebraic Degree              |
    | Component Function +-----+---+----+----+----+----+----+---+-----+
    |                    |  8  | 7 | 6  | 5  | 4  | 3  | 2  | 1 |  0  |
    +--------------------+-----+---+----+----+----+----+----+---+-----+
    |        Y_0         |  0  | 3 | 15 | 31 | 28 | 29 | 14 | 3 |  1  |
    |        Y_1         |  0  | 3 | 12 | 34 | 40 | 33 | 12 | 4 |  1  |
    |        Y_2         |  0  | 5 | 17 | 24 | 40 | 24 | 11 | 3 |  0  |
    |        Y_3         |  0  | 2 | 11 | 31 | 34 | 27 | 15 | 5 |  1  |
    |        Y_4         |  0  | 5 | 15 | 28 | 33 | 24 | 13 | 5 |  0  |
    |        Y_5         |  0  | 5 | 11 | 25 | 41 | 25 | 16 | 4 |  1  |
    |        Y_6         |  0  | 4 | 15 | 29 | 27 | 32 | 18 | 4 |  1  |
    |        Y_7         |  0  | 4 | 14 | 32 | 35 | 30 | 16 | 3 |  0  |
    +--------------------+-----+---+----+----+----+----+----+---+-----+
    | Expected Value     | 1/2 | 4 | 14 | 28 | 35 | 28 | 14 | 4 | 1/2 |
    +--------------------+-----+---+----+----+----+----+----+---+-----+

    Figure 4: SM4 S-box Component Functions Algebraic Degree And Terms
```

The header would be possible to be rendered in v3 with `colspan` and `rowspan`. Currently this is just ASCIIArt...

**Comment by reschke** [comment]
That's a good example, but I don't believe it's a use case for \<tfoot>.

\<tfoot> would cause the last line to be repeated on every page break. This is not what you want here, right? What's needed is somewhat limited control of the row styles.

**Comment by ronaldtse** [comment]
@reschke according to RFC 7991, `<tfoot>` is actually the footer row?

```
2.57.  <tfoot>

   A container for a set of footer rows for a table.
   This element appears as a child element of <table> (Section 2.54).
   Content model:
   One or more <tr> elements (Section 2.61)
```

**Comment by ronaldtse** [comment]
But @reschke you have a good point. In the case of this table, we don't want the last row to be on every page the table flows over. I agree that more fine-grained control of row/column styling is best.

**Comment by stpeter** [comment]
We seem to have a use case for this - see Section 5.1 of RFC 8855 - so the sense of the XML change management team is that it's reasonable to retain this in the v3 vocabulary.

**Comment by reschke** [comment]
But that doesn't seem to be a proper use of \<tfoot>, unless you really really want these three lines to be repeated at the end of the table in case of a page break inside the table.

**Comment by stpeter** [comment]
Hmm, I see your point. :-)

**Comment by reschke** [comment]
I may have to take this back.

I recently encountered a use case where HTML's \<tfoot> is used outside pagination: table summary lines that do not take part in sorting (when a JS module makes a table sortable). 

Proposal: close this issue. I was wrong.
