### ISSUE TITLE
cref anchor and display attributes

### ISSUE THREAD

**Issue by miekg** [rfc-format/draft-iab-xml2rfc-v3-bis#74]
Is a `cref` with an anchor and display=false allowed to be referenced?

**Comment by reschke** [comment]
In rfc2629.xslt, I recently implemented display=false (<https://github.com/reschke/xml2rfc/commit/67efc927419be59a6b9e096ce7cfaaf659f868f5>) and chose to emit an error message and not generate the link.

xml2rfcv3 currently does not seem to support display=false; in HTML output the attribute is ignored, in TXT output it aborts (see <https://trac.tools.ietf.org/tools/xml2rfc/trac/attachment/ticket/515/> and <https://trac.tools.ietf.org/tools/xml2rfc/trac/attachment/ticket/516/>).

For the spec, the simplest approach would be to just state that this is an error.

**Comment by reschke** [comment]
xml2rfc recently has improved, but it still generates broken HTML output for the \<xref>, see https://trac.tools.ietf.org/tools/xml2rfc/trac/ticket/523

**Comment by reschke** [comment]
@interim-rfc-series-project-manager  - this can IMHO be closed.
