### ISSUE TITLE
unclear use of type attribute on artwork

### ISSUE THREAD

**Issue by reschke** [rfc-format/draft-iab-xml2rfc-v3-bis#75]
Please clarify what role (if any) the type attribute plays in detecting whether the contents of the artwork element is to be considered text or SVG (the two options allowed by the grammar).

(FWIW, the type attribute is not needed for this).

**Comment by hlflanagan** [comment]
I'm planning to follow Henrik's guidance in draft-levkowetz-xml2rfc-v3-implementation-notes (section 3.1.3). Specifically: "Require the "type" attribute to have a value if the "src" attribute is specified, and let it describe the format.  If any action should be taken on the basis of one of the preferred values appearing or a different value appearing, add text to indicate so." Regarding additional attributes to capture the artwork format in place of call-flow and hex-dump, I need more information on common usage patterns for them.

**Comment by reschke** [comment]
At least for inlined svg content, this seems to just add completely useless burden to authors. It violates that DRY principle.

If the artwork element contains whitespace and exactly one svg:svg child node, why require the author to insert a type attribute? It really doesn't make any sense to me.

**Comment by jrlevine** [comment]
We think it's a robustness feature, e.g., if the SVG has a syntax error it would be unfortunate to silently turn it into text.

**Comment by reschke** [comment]
> We think it's a robustness feature, e.g., if the SVG has a syntax error it would be unfortunate to silently turn it into text.

 But that's not what would happen. A syntax error would cause the full document not to parse.

Please re-open.

**Comment by jrlevine** [comment]
Wait a minute. If there's no tag, how does it tell that something is SVG? And if it's SVG with an error, what is that?

How about if I'm writing a draft about Common Errors in SVG where I *want* to show bad SVG?

**Comment by reschke** [comment]
If you want to show bad SVG in artwork, you'll need to write it as text, not XML. The type attribute by definition does not affect XML parsing.

So if you want to the artwork to display
~~~
<svg<
~~~

you'll need to write:
~~~
<artwork>&lt;svg&lt,</artwork>
~~~

If you did 
~~~
<artwork><svg<</artwork>
~~~

the whole document would not parse anymore.

There is no ambiguity here that the type attribute would help with.

**Comment by reschke** [comment]
@jrlevine - with all due respect, the argument in favor of closing this ticket is plainly incorrect. Could you please reopen the ticket?

**Comment by jrlevine** [comment]
We understand that it's redundant, but we still think the explicit tag makes the author's intention clear.

**Comment by reschke** [comment]
That doesn't make any sense.

What could be the intention other than to have the SVG rendered? Could you please provide *some* example?

This is a case of where the authoring format is needlessly complex.
