### ISSUE TITLE
Create a artworkGroup element

### ISSUE THREAD

**Issue by jimsch** [rfc-format/draft-iab-xml2rfc-v3-bis#76]
The current method of putting some of the artwork in a data URL makes for both difficult reading and difficult editing.  It would be much cleaner to have an artwork group element which allows for multiple artwork elements.  This would allow both for easier editing, and potentially the ability to have more than two alternatives.  One example would be to have SVG, ASCII art and another format to exist at the same time.  This may be useful for some future display formats.

**Comment by levkowetz** [comment]
I agree.

**Comment by reschke** [comment]
This was addressed by the addition of \<artset> in #89 

@interim-rfc-series-project-manager  - this issue can be closed.

**Comment by jrlevine** [comment]
addressed by &lt;artset>
