### ISSUE TITLE
true and false interchanged for newline attribute of dl element

### ISSUE THREAD

**Issue by msvoelker** [rfc-format/draft-iab-xml2rfc-v3-bis#77]
In section 2.19.3. "newline" Attribute, _true_ needs to be replaced with _false_ and _false_ needs to be replaced with _true_.

**Comment by reschke** [comment]
See also mailing list thread ending in <https://mailarchive.ietf.org/arch/msg/xml2rfc-dev/O7oPao8eumcKQPXHXqhf1pTRdp0>

**Comment by reschke** [comment]
@i-rse - this issue can be closed.
