### ISSUE TITLE
HTML: date information for RFCs

### ISSUE THREAD

**Issue by reschke** [rfc-format/draft-iab-xml2rfc-v3-bis#80]
<https://greenbytes.de/tech/webdav/rfc7992.html#document-information> suggests YYYY-MM-DD, but RFCs have been published without day-of-month information up to now.

**Comment by jrlevine** [comment]
In 7992 there are three examples, one with a time to the second, one with a day, one just a month. I interpret that as allowing any of those, including our approach of month only, except for 1 April.

**Comment by reschke** [comment]
I was talking about the boilerplate, not other timestamps.

For RFCs (see for instance https://www.rfc-editor.org/rfc/rfc9000.html), we use "Month YYYY" (maybe except April 1st). So RFC 7992 is inconsistent with that.

Please reopen.

**Comment by jrlevine** [comment]
I can see how it's a bug in 7992, since the style guide says no date except for April 1.

**Comment by reschke** [comment]
Indeed. Can we move the issue? If we can't I can enter a new one.
