### ISSUE TITLE
Styling section listing contributors

### ISSUE THREAD

**Issue by reschke** [rfc-format/draft-iab-xml2rfc-v3-bis#81]
see also #1 and #19 

Authors frequently want to include an appendix listing contributors in addition to authors.

While this is possible as just prose, it's not possible to style this in a way similar to the "Authors" section. It's debatable whether this is actually desirable, but we see cases where authors just use the \<artwork> element to get what they want.

That said, <https://tools.ietf.org/html/draft-flanagan-7322bis-03#section-4.11> says:

>    The Contributors section may include brief statements about the
>    nature of particular contributions (e.g., "Sam contributed
>    Section 3"), and it may also include affiliations of listed
>    contributors.  At the discretion of the author(s), contact addresses
>    may also be included in the Contributors section, for those
>    contributors whose knowledge makes them useful future contacts for
>    information about the RFC.  The format of any contact information
>    _should be similar to the format of information in the Author's
>    Address section._

(emphasis mine)

This is currently impossible because we don't allow authors to control line breaks in prose.

A \<br> element would fix this (but see #37).

An alternative way is implemented in rfc2629.xslt: <https://greenbytes.de/tech/webdav/rfc2629xslt/rfc2629xslt.html#ext.element.contributor>

**Comment by martinthomson** [comment]
#19 seems to be a better result.

**Comment by reschke** [comment]
Well, that one was closed. It also has the problem that it suggests an incompatible change, in that existing code that checks for \<author> tags would be misled.

**Comment by reschke** [comment]
Note that the possibility of a "Contributors" section already was documented in https://tools.ietf.org/html/rfc7322#section-4.11>, dated September 2014. We really should find a way to produce that with the v3 vocabulary.

**Comment by martinthomson** [comment]
By which you refer to "The format of any contact information should be similar to the format of information in the Author's Address section."  I agree.
