### ISSUE TITLE
README should link to rendered draft

### ISSUE THREAD

**Issue by jyasskin** [rfc-format/draft-iab-xml2rfc-v3-bis#82]
Like, for example, https://github.com/cbor-wg/CBORbis/blob/master/README.md links to both an [Editor's copy](https://cbor-wg.github.io/CBORbis/draft-ietf-cbor-7049bis.html) (that's built using TravisCI into the gh-pages branch) and a [Working Group Draft](https://tools.ietf.org/html/draft-ietf-cbor-7049bis).

**Comment by paulehoffman** [comment]
Building the rendered draft is *much* more difficult for this document than typical Internet-Drafts because of the interaction with making the RNG.
