### ISSUE TITLE
Errors while building

### ISSUE THREAD

**Issue by jyasskin** [rfc-format/draft-iab-xml2rfc-v3-bis#83]
When running `make` from a clean checkout (`git reset --hard origin/master; git clean -fxd`), the `tclsh xml2rfc.tcl xml2rfc draft-iab-rfc7991bis.redxml draft-iab-rfc7991bis.unpg.txt.unpg` command pops up a window showing

> Can't resolve xref target RFC7322 around input line 97
> key not known
>    while executing
>"::${basename}::pkgconfig get scriptdir,runtime"

and then fails with an exit code of 1.

> $ saxon --version
> SAXON 6.5.5 from Michael Kay

**Comment by reschke** [comment]
The build probably should be modified to use xml2rfv v2/v3 instead.
