### ISSUE TITLE
<aside> can't contain blockquote

### ISSUE THREAD

**Issue by miekg** [rfc-format/draft-iab-xml2rfc-v3-bis#84]
similar to #35, an <aside> can contain a lot of things, but no `<blockquote>`

**Comment by reschke** [comment]
Feature request for xml2rfc: https://trac.tools.ietf.org/tools/xml2rfc/trac/ticket/524

**Comment by reschke** [comment]
@interim-rfc-series-project-manager - this issue can be closed

**Comment by reschke** [comment]
@jrlevine - see https://trac.tools.ietf.org/tools/xml2rfc/trac/changeset/3772

**Comment by jrlevine** [comment]
Robert Sparks, Peter St A, Henrik, and I finally talked last week. They all felt that was an oversight and it should be allowed. That and the indent in <t> are supposed to be the last changes to the grammar. Can you un-revert that one?

**Comment by reschke** [comment]
I think you'll need to revert it.

**Comment by stpeter** [comment]
Closing in favor of https://github.com/rfc-format/draft-iab-xml2rfc-v3-bis/issues/190
