### ISSUE TITLE
need a way to horizontally align <table>s

### ISSUE THREAD

**Issue by reschke** [rfc-format/draft-iab-xml2rfc-v3-bis#9]
(from https://tools.ietf.org/tools/xml2rfc/trac/ticket/324)

This was possible in v2 with texttable/@align.

**Comment by paulehoffman** [comment]
Please say more about the "need" here. What semantically is being lost without this? Can tables be misinterpreted without such alignment?

**Comment by reschke** [comment]
No, but I don't see how this is relevant.

We do have attributes to control same-page-placement, which is presentation only, and only applies to paged media, after all.

**Comment by reschke** [comment]
FWIW, a quick & dirty statistic over AUTH48 XML shows ~1700 text tables, of which ~120 were aligned left using the align attribute (the default would be centered).

**Comment by levkowetz** [comment]
+1, see additional reasoning in issue #40 (duplicate issue).  Experience with the limitation of the v3 text formatter indicates that removing this ability is detrimental.

**Comment by paulehoffman** [comment]
Fixed in the -01
